import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] });
const alfabeto = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split('').map(l => l);

export default function Home() {
  const palavra = "lapis";
  const [letrasUtilizadas, setLetra] = useState(['']);

  const handleChange = (letra: string) => {
    let l = [...letrasUtilizadas];
    if (!l.includes(letra)) {
      l.push(letra);
      setLetra(l);
    }
  };

  const handleReset = () => { setLetra([]); }
  return (
    <>
      <Head>
        <title>Jogo da Forca</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>
            Jogo Da Forca
          </h1>
        </div>
        <h3>Dica: Tem na escola</h3>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/forca_img.jpg"
            alt="forca img"
            width={280}
            height={280}
            priority
          />
          <div>
            {
              palavra.split('').map((letra, i) => (<span key={i + '_palavra'} className={letra}>_&ensp;</span>)
              )
            }
          </div>
        </div>
        <div>
          <p>Palavras do alfabeto já utilizadas: {letrasUtilizadas.map((l, i) => (<span key={i + '_letras'}>{l}&ensp;</span>))}</p>
          <p>Teclado</p>
          {
            alfabeto.map((l, i) => (<button style={{ marginLeft: '5px' }} key={i + '_alfabeto'} onClick={() => handleChange(l)}>{l}</button>))
          }
          <p><button onClick={handleReset}>Reset</button></p>
        </div>
      </main>
    </>
  )
}
